#!/bin/bash

function upload(){
    echo "The backup contains this stuff:"
    files=(`ls`)
    index=0
    for i in "${files[@]}"
        do
            index=`expr $index + 1`
            echo "   "$index"." $i
        done
    echo
    echo "Enter the lines you want to upload separated with space or a for everything. Once done, press enter."
    read -a multioption
    index=0
    if [ "${multioption[@]}" = a ]; then
        echo "Uploading everything from the /sdcard/ folder in the device..."
        adb push * /sdcard/
    else
        echo "Your selection is:"
        for i in "${multioption[@]}"
            do
                echo ${files[`expr $i - 1`]}
            done
        echo
        index=0
        for i in "${multioption[@]}"
            do
                echo "Uploading "${files[`expr $i - 1`]} "..."
                adb push ${files[`expr $i - 1`]} /sdcard/
            done
        echo
   fi
}

function download(){
    echo "The /sdcard/ folder in the device contains this stuff:"
    files=(`adb shell ls /sdcard/`)
    index=0
    for i in "${files[@]}"
        do
            index=`expr $index + 1`
            echo "   "$index"." $i
        done
    echo
    echo "Enter the lines you want to download separated with space or a for everything. Once done, press enter."
    read -a multioption
    index=0
    if [ $multioption = a ]; then
        echo "Downloading everything from the /sdcard/ folder in the device..."
        adb pull /sdcard/
    else
        echo "Your selection is:"
        for i in "${multioption[@]}"
            do
                echo ${files[`expr $i - 1`]}
            done
        echo
        index=0
        for i in "${multioption[@]}"
            do
                echo "Downloading "${files[`expr $i - 1`]} "..."
                adb pull /sdcard/${files[`expr $i - 1`]}
            done
        echo
    fi
}

function finish(){
    echo "Finished."
    echo
}

function cancel(){
    echo "Cancelled."
    echo
}

devicestatus=`adb get-state`
if [ -z $devicestatus ]; then
    echo "There is no connected device or it is in wrong mode."
else
    if [ $devicestatus = "device" ] || [ $devicestatus = "recovery" ]; then
        echo "Device detected with serial number `adb get-serialno`."
        echo
        echo "Select an operation:"
        echo " d -> To download files from device."
        echo " u -> To upload files to device."
        echo " c -> To cancel and exit."
        read option
        echo
        case $option in
            u)
                upload
                finish
            ;;
            d)
                download
                finish
            ;;
            c)
                cancel
            ;;
            *)
                echo "Woops!! I don't understand!! What do you mean by $option?"
        esac
    fi
fi
